[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "starlette-app"
version = "0.0.1"
dependencies = ["starlette"]

[project.optional-dependencies]
dev = ["uvicorn"]
